### ISSUE TITLE
OSX delay before ready

### ISSUE THREAD

**Issue by sschueller** [stephenh/mirror#34]
Thanks for the great tool.

One thing I have noticed wenn syncing between a Debian machine (server) and OSX (client) is that while Debian will react right away to file changes after start, OSX needs 1-2 minutes before it reacts. Files changed in that time are not synced unless touched again. Is there something I can do to fix this or figure out what is causing it? Or if there was a way to detect it and notify via output wenn OSX is ready?

I am running the docker version

**Comment by stephenh** [comment]
Hey; I don't have any good ideas; I assume you're using watchman and have a new/latest version of it?

Mirror has a two phase start up of: a) watchman, please tell me all the files in directory X, and then b) watchman, please tell me all files that changed since timestamp X, and X is recorded at the start (from the response of) a), so my understanding of watchman semantics is that they should line up/not have anything dropped.

Here's where the a) clock value comes back:

https://github.com/stephenh/mirror/blob/master/src/main/java/mirror/watchman/WatchmanFileWatcher.java#L190

If you want to poke around, you could put some logging statements/something around there, and see if that shows anything interesting.
