### ISSUE TITLE
./gradlew shadowJar produces wrong jar name

### ISSUE THREAD

**Issue by ediphy-azorab** [stephenh/mirror#35]
It's possibly an artifact of my environment, but the output of the shadowJar task is called `mirror.jar` on my system, not `mirror-all.jar`.

It's simple enough to fix up the build scripts, but I don't want to do it if it's only my box it's happening on.

**Comment by stephenh** [comment]
Huh, you're right. This probably changed when I bumped a gradle version/something and didn't realize it.

I started changing all of the `mirror-all`s to just `mirror`, like you did in in #36, but also upgraded the gradle shadow plugin, and turns out that fixed it.

So, probably was a gradle upgrade not agreeing with an old version of the shadow plugin, but looks to be fixed now. Thanks!
