### ISSUE TITLE
CentOS docker image

### ISSUE THREAD

**Issue by rameshar16** [stephenh/mirror#55]
Hi @stephenh,
I am seeing the current image base os is Debian, Can we use CentOs instead of debain?

Thanks and Regards,
Ramesh AR

**Comment by stephenh** [comment]
I don't think what OS the docker container uses should matter, because users are not expected to log in to it and really `cd` / `ls` around, they should just run the `docker ...` commands and not care whether it's Debian or CentOS or Alpine.

So, my brief answer is no. If you have an objective reason like image size (which afaiu the nod usually goes to Alpine for smallest image sizes), I'm open to a PR that changes it for some explicit reason, but otherwise if it's just personal preference, you can use your own CentOS-based dockerfile.

**Comment by rameshar16** [comment]
our security compliance team not allowing to use Debian and alpine os based images. I have built the centos based image.But, the build threw few errors/warns and skipped them by adding the below.
**./configure --disable-dependency-tracking --enable-lenient**

The image is working as expected.
